name: pulmap
services:
  pulmap_test_solr:
    type: solr:custom
    overrides:
      image: pulibrary/pulmap-solr:8.4
      command: /opt/solr/server/scripts/lando-start.sh
    portforward: true
    core: pulmap-core-test
    config:
      dir: "solr/conf"
  pulmap_development_solr:
    type: solr:custom
    overrides:
      image: pulibrary/pulmap-solr:8.4
      command: /opt/solr/server/scripts/lando-start.sh
    portforward: true
    core: pulmap-core-dev
    config:
      dir: "solr/conf"
  pulmap_database:
    type: postgres:10
    portforward: true
proxy:
  pulmap_test_solr:
    - pulmap.test.solr.lndo.site:8983
  pulmap_development_solr:
    - pulmap.dev.solr.lndo.site:8983
