# require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  RunRailsCops: true

  DisplayCopNames: true

  Include:
  - '**/Rakefile'

  Exclude:
  - 'bin/*'
  - 'db/**/*'
  - 'vendor/**/*'

# TODO: reduce method complexity in omniauth callback controller.
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

# Metrics/LineLength:
#   Enabled: false

# TODO: Add top-level class and module documentation.
Style/Documentation:
  Enabled: false