# require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  RunRailsCops: true

  DisplayCopNames: true

  Include:
  - '**/Rakefile'

  Exclude:
  - 'bin/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'config/initializers/*'

# TODO: Reduce method complexity in omniauth callback controller.
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'Rakefile'
    # TODO: Refactor add_show_tools_partial procs.
    - 'app/controllers/catalog_controller.rb'

# TODO: Add top-level class and module documentation.
Style/Documentation:
  Enabled: false

# Overrides method in blacklight. Must use method name.
Style/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'