cache: bundler
language: ruby
sudo: false
notifications:
  email: false

rvm:
  - 2.1.4

before_script:
  - cp config/database.yml.tmpl config/database.yml

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake ci