development:
  host: localhost
  port: 6379
  db: 0
test:
  host: localhost
  port: 6379
  db: 0
production: &production
  host: <%= ENV['PULMAP_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['PULMAP_REDIS_PORT'] || '6379' %>
  db: <%= ENV['PULMAP_REDIS_DB'] || 0 %>
staging:
  <<: *production
