local:
  service: Disk
  root: <%= Rails.root.join("tmp","storage") %>

google:
  service: GCS
  credentials: <%= ENV["GOOGLE_CLOUD_CREDENTIALS"] %>
  project: <%= ENV["GOOGLE_CLOUD_PROJECT"] %>
  bucket: <%= ENV["GOOGLE_CLOUD_BUCKET"] %>
